In [1]:
import pandas as pd

In [2]:
smi=pd.read_csv("smi.txt", index_col="Ticker")

In [3]:
smi

                                   Company
Ticker
CSGN.VX             Credit Suisse Group AG
NESN.VX                        Nestlé S.A.
SGSN.VX                             SGS SA
UBSG.VX                       UBS Group AG
LONN.VX                    Lonza Group Ltd
ROG.VX                    Roche Holding AG
SIK.VX                             Sika AG
UHR.VX                 The Swatch Group AG
NOVN.VX                        Novartis AG
ABBN.VX                            ABB Ltd
GIVN.VX                        Givaudan SA
SLHN.VX              Swiss Life Holding AG
BAER.VX             Julius Baer Group Ltd.
GEBN.VX                         Geberit AG
ADEN.VX                    Adecco Group AG
ZURN.VX          Zurich Insurance Group AG
SCMN.VX                        Swisscom AG
CFR.VX   Compagnie Financière Richemont SA
LHN.VX                   LafargeHolcim Ltd
SREN.VX                       Swiss Re Ltd

In [4]:
import pandas_datareader as pdr
a=pdr.get_data_yahoo(list(smi.index), start=pd.Timestamp("2017-01-01"))

/opt/conda/lib/python3.6/site-packages/pandas_datareader/base.py:230: SymbolWarning: Failed to read symbol: 'SIK.VX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

In [5]:
a

Attributes       High                                                          \
Symbols       ABBN.VX    ADEN.VX    BAER.VX     CFR.VX    CSGN.VX     GEBN.VX
Date
2017-01-03  21.870001  68.150002  47.790001  68.500000  15.226400  413.000000
2017-01-04  21.790001  69.699997  48.459999  67.099998  15.689600  410.700012
2017-01-05  21.790001  69.699997  48.430000  66.599998  15.593100  410.700012
2017-01-06  21.969999  69.500000  48.340000  67.500000  15.400100  411.299988
2017-01-09  21.959999  69.650002  47.950001  68.349998  15.467700  411.399994
2017-01-10  22.120001  70.150002  47.490002  71.199997  15.380800  412.299988
2017-01-11  22.790001  70.400002  47.630001  71.500000  15.535200  414.299988
2017-01-12  22.610001  71.550003  47.279999  77.550003  15.564200  413.600006
2017-01-13  22.709999  71.900002  48.139999  77.400002  15.737900  414.399994
2017-01-16  22.780001  70.050003  48.209999  77.300003  15.429100  416.899994
2017-01-17  22.500000  70.000000  48.040001  77.199997  15.361500  430.000000
2017-01-18  22.500000  70.199997  48.169998  76.900002  15.004500  427.000000
2017-01-19  22.730000  70.949997  47.720001  76.699997  15.014200  424.899994
2017-01-20  22.889999  71.300003  47.250000  76.800003  15.033500  423.799988
2017-01-23  22.830000  71.050003  46.459999  76.750000  14.811500  422.399994
2017-01-24  22.950001  71.650002  46.310001  76.800003  14.801900  422.299988
2017-01-25  23.530001  72.800003  47.270000  78.449997  15.390500  427.000000
2017-01-26  23.870001  72.949997  47.919998  78.150002  15.583500  431.299988
2017-01-27  23.820000  72.650002  47.520000  78.099998  14.975600  431.399994
2017-01-30  23.840000  71.500000  46.209999  76.949997  14.859800  426.200012
2017-01-31  23.750000  71.400002  46.980000  78.250000  14.965900  423.299988
2017-02-01  23.780001  71.650002  48.840000  77.349998  14.734300  424.299988
2017-02-02  23.540001  71.400002  46.990002  76.800003  14.676400  424.200012
2017-02-03  23.510000  71.349998  46.770000  76.000000  14.608900  423.600006
2017-02-06  23.490000  71.500000  46.939999  75.449997  14.618500  423.200012
2017-02-07  23.469999  71.250000  47.259998  75.199997  14.483400  423.500000
2017-02-08  22.900000  70.699997  47.590000  74.849998  14.387000  425.500000
2017-02-09  22.860001  69.900002  47.410000  74.400002  14.145700  427.200012
2017-02-10  23.040001  70.500000  47.540001  75.400002  14.348400  429.299988
2017-02-13  23.049999  71.349998  47.860001  76.349998  14.377300  429.500000
...               ...        ...        ...        ...        ...         ...
2018-04-30  23.280001  66.300003  59.439999  94.699997  16.875000  428.100006
2018-05-02  23.530001  66.620003  59.919998  95.540001  16.855000  431.299988
2018-05-03  23.450001  66.660004  60.080002  95.500000  16.740000  449.700012
2018-05-04  23.480000  66.540001  59.959999  95.320000  16.415001  444.600006
2018-05-07  23.830000  67.440002  61.020000  95.699997  16.594999  445.899994
2018-05-08  23.990000  66.059998  61.080002  95.919998  16.629999  447.600006
2018-05-09  24.120001  64.440002  61.580002  96.639999  16.870001  448.200012
2018-05-11  24.230000  64.919998  63.259998  96.720001  17.200001  449.500000
2018-05-14  24.100000  64.660004  62.919998  98.400002  17.110001  447.000000
2018-05-15  23.990000  63.840000  63.160000  98.000000  17.100000  445.700012
2018-05-16  24.040001  63.660000  62.959999  98.199997  16.975000  443.399994
2018-05-17  24.120001  63.700001  62.900002  99.019997  16.865000  446.100006
2018-05-18  24.350000  63.700001  62.799999  94.320000  16.920000  446.799988
2018-05-22  24.600000  64.480003  63.299999  93.820000  16.945000  446.899994
2018-05-23  24.370001  63.680000  63.000000  92.400002  16.865000  444.100006
2018-05-24  23.910000  62.560001  61.900002  93.379997  16.530001  440.100006
2018-05-25  23.780001  62.500000  61.500000  93.339996  16.389999  440.200012
2018-05-28  23.629999  62.160000  61.299999  94.059998  16.309999  439.000000
2018-05-29  23.260000  61.040001  60.820000  92.339996  15.945000  433.500000
2018-05-30  22.910000  60.299999  59.759998  92.059998  15.485000  431.100006
2018-05-31  22.959999  60.459999  59.200001  92.099998  15.530000  434.200012
2018-06-01  22.990000  60.680000  58.939999  91.739998  15.550000  436.299988
2018-06-04  23.040001  60.939999  59.419998  92.180000  15.640000  437.399994
2018-06-05  22.980000  60.380001  59.299999  92.680000  15.585000  437.700012
2018-06-06  22.830000  60.220001  58.840000  93.300003  15.295000  440.500000
2018-06-07  22.990000  60.439999  59.840000  93.739998  15.550000  441.299988
2018-06-08  22.780001  59.959999  59.200001  92.660004  15.370000  440.500000
2018-06-11  22.910000  60.220001  60.360001  92.779999  15.760000  442.500000
2018-06-12  23.049999  60.400002  60.700001  93.040001  15.815000  443.700012
2019-02-14  19.645000  52.799999  41.189999  73.500000  12.290000  393.700012

Attributes                                               ...      Adj Close  \
Symbols    GIVN.VX     LHN.VX     LONN.VX    NESN.VX     ...        NOVN.VX
Date                                                     ...
2017-01-03  1881.0  54.400002  166.268997  73.599998     ...      69.855576
2017-01-04  1873.0  53.849998  169.326004  73.300003     ...      69.204025
2017-01-05  1879.0  53.950001  170.529999  74.099998     ...      69.715965
2017-01-06  1879.0  54.150002  171.363998  74.599998     ...      69.576340
2017-01-09  1876.0  54.400002  171.177994  74.900002     ...      69.809036
2017-01-10  1876.0  53.900002  171.363998  74.800003     ...      70.181351
2017-01-11  1862.0  53.900002  175.160995  74.849998     ...      69.297104
2017-01-12  1854.0  53.549999  172.567993  74.599998     ...      67.761314
2017-01-13  1859.0  54.450001  171.826996  74.650002     ...      67.947464
2017-01-16  1836.0  54.200001  172.475006  74.500000     ...      67.109756
2017-01-17  1829.0  52.500000  170.436996  74.050003     ...      66.411667
2017-01-18  1827.0  52.000000  170.623001  73.949997     ...      67.202827
2017-01-19  1830.0  51.650002  171.363998  73.900002     ...      66.178970
2017-01-20  1820.0  51.400002  171.363998  73.349998     ...      65.992813
2017-01-23  1819.0  51.299999  170.992996  73.300003     ...      65.201645
2017-01-24  1828.0  53.099998  172.011993  73.400002     ...      64.736252
2017-01-25  1840.0  54.950001  174.419998  73.800003     ...      66.318588
2017-01-26  1842.0  55.250000  174.606003  73.800003     ...      66.923599
2017-01-27  1830.0  54.599998  173.031006  73.300003     ...      66.923599
2017-01-30  1866.0  54.150002  170.992996  73.050003     ...      67.016678
2017-01-31  1790.0  53.599998  169.604004  72.699997     ...      67.435532
2017-02-01  1777.0  54.599998  163.953003  73.250000     ...      67.528610
2017-02-02  1770.0  54.299999  162.192993  72.750000     ...      67.109756
2017-02-03  1730.0  55.549999  162.934006  73.099998     ...      67.900917
2017-02-06  1733.0  55.450001  162.378998  73.150002     ...      68.273239
2017-02-07  1761.0  54.799999  162.378998  73.199997     ...      68.831711
2017-02-08  1772.0  54.549999  163.397003  74.449997     ...      68.971329
2017-02-09  1789.0  55.799999  163.953003  74.400002     ...      69.809036
2017-02-10  1780.0  56.750000  164.509003  74.050003     ...      69.809036
2017-02-13  1771.0  56.950001  165.712997  73.900002     ...      70.274437
...            ...        ...         ...        ...     ...            ...
2018-04-30  2235.0  55.360001  246.199997  77.260002     ...      76.699997
2018-05-02  2229.0  55.840000  248.399994  76.980003     ...      76.400002
2018-05-03  2230.0  56.020000  247.199997  76.239998     ...      76.019997
2018-05-04  2218.0  56.299999  258.399994  76.360001     ...      76.760002
2018-05-07  2238.0  56.599998  266.799988  77.739998     ...      77.599998
2018-05-08  2245.0  56.000000  263.000000  77.779999     ...      77.720001
2018-05-09  2266.0  55.020000  263.200012  77.400002     ...      77.699997
2018-05-11  2286.0  53.520000  266.600006  77.900002     ...      77.559998
2018-05-14  2287.0  53.119999  267.799988  77.620003     ...      78.220001
2018-05-15  2284.0  53.639999  267.100006  77.279999     ...      77.980003
2018-05-16  2282.0  53.459999  264.200012  77.059998     ...      77.779999
2018-05-17  2285.0  53.599998  264.500000  77.220001     ...      77.639999
2018-05-18  2273.0  53.680000  267.700012  77.559998     ...      77.000000
2018-05-22  2283.0  53.880001  273.200012  77.480003     ...      76.680000
2018-05-23  2255.0  53.680000  270.700012  76.000000     ...      76.160004
2018-05-24  2243.0  52.759998  272.399994  76.059998     ...      75.660004
2018-05-25  2243.0  52.759998  270.200012  76.760002     ...      75.559998
2018-05-28  2250.0  52.799999  272.100006  77.099998     ...      75.779999
2018-05-29  2229.0  52.020000  269.500000  76.820000     ...      74.599998
2018-05-30  2230.0  51.459999  269.399994  76.339996     ...      74.519997
2018-05-31  2233.0  51.900002  269.899994  75.820000     ...      72.959999
2018-06-01  2232.0  51.860001  268.200012  75.360001     ...      74.699997
2018-06-04  2243.0  51.799999  269.799988  75.620003     ...      74.699997
2018-06-05  2214.0  51.939999  269.200012  75.540001     ...      73.959999
2018-06-06  2219.0  51.980000  269.500000  74.699997     ...      73.980003
2018-06-07  2236.0  52.439999  271.399994  74.419998     ...      74.260002
2018-06-08  2211.0  52.160000  269.000000  73.720001     ...      73.860001
2018-06-11  2236.0  52.459999  272.899994  74.500000     ...      74.500000
2018-06-12  2241.0  52.700001  274.200012  74.800003     ...      74.680000
2019-02-14  2484.0  47.900002  287.200012  89.900002     ...      89.760002

Attributes                                                                \
Symbols         ROG.VX     SCMN.VX SGSN.VX SIK.VX     SLHN.VX    SREN.VX
Date
2017-01-03  236.000000  410.591125  2094.0    NaN  296.500000  82.766937
2017-01-04  238.100006  417.127197  2091.0    NaN  298.500000  83.148743
2017-01-05  241.199997  423.754028  2104.0    NaN  298.000000  82.342712
2017-01-06  241.300003  424.026398  2101.0    NaN  298.299988  82.130600
2017-01-09  241.899994  423.209351  2114.0    NaN  297.100006  81.494255
2017-01-10  243.399994  419.305878  2098.0    NaN  294.299988  81.324562
2017-01-11  240.800003  418.761200  2116.0    NaN  295.200012  81.579102
2017-01-12  235.899994  416.673309  2121.0    NaN  294.299988  80.857918
2017-01-13  239.000000  418.670441  2146.0    NaN  295.600006  81.791214
2017-01-16  235.600006  412.406677  2139.0    NaN  292.600006  79.797340
2017-01-17  234.699997  410.681915  2090.0    NaN  292.899994  79.161003
2017-01-18  235.600006  408.140137  2088.0    NaN  292.399994  78.821617
2017-01-19  233.000000  405.507568  2090.0    NaN  296.399994  78.482231
2017-01-20  233.500000  401.059387  2094.0    NaN  295.200012  78.439804
2017-01-23  232.199997  398.699188  2051.0    NaN  294.200012  78.100426
2017-01-24  231.399994  397.155914  2076.0    NaN  296.000000  78.567078
2017-01-25  234.800003  397.609802  2097.0    NaN  303.100006  79.924606
2017-01-26  235.699997  396.974365  2101.0    NaN  302.899994  79.161003
2017-01-27  236.300003  396.702026  2104.0    NaN  300.799988  79.754921
2017-01-30  234.000000  393.433990  2088.0    NaN  298.500000  78.524658
2017-01-31  233.000000  394.886475  2092.0    NaN  299.100006  78.142853
2017-02-01  237.500000  393.070892  2073.0    NaN  306.200012  79.203423
2017-02-02  233.500000  390.619843  2074.0    NaN  303.299988  79.415535
2017-02-03  235.800003  392.526215  2076.0    NaN  308.100006  80.094299
2017-02-06  236.100006  391.436890  2062.0    NaN  306.500000  79.670074
2017-02-07  238.500000  394.523376  2068.0    NaN  306.700012  79.585228
2017-02-08  237.399994  399.970062  2085.0    NaN  303.899994  79.839760
2017-02-09  239.899994  403.328857  2092.0    NaN  308.100006  80.773064
2017-02-10  239.899994  403.328857  2092.0    NaN  308.100006  80.773064
2017-02-13  240.000000  401.331726  2114.0    NaN  311.299988  79.924606
...                ...         ...     ...    ...         ...        ...
2018-04-30  220.850006  477.000000  2417.0    NaN  348.500000  94.660004
2018-05-02  223.649994  460.299988  2428.0    NaN  349.700012  93.500000
2018-05-03  224.949997  456.000000  2423.0    NaN  346.600006  93.220001
2018-05-04  225.800003  455.500000  2437.0    NaN  347.500000  92.800003
2018-05-07  227.850006  460.700012  2456.0    NaN  350.500000  93.620003
2018-05-08  225.699997  458.299988  2482.0    NaN  353.299988  94.279999
2018-05-09  226.000000  458.899994  2506.0    NaN  357.899994  94.639999
2018-05-11  222.149994  460.399994  2515.0    NaN  360.299988  95.139999
2018-05-14  224.800003  458.200012  2509.0    NaN  358.500000  94.279999
2018-05-15  225.699997  454.899994  2490.0    NaN  360.399994  94.519997
2018-05-16  226.199997  450.700012  2500.0    NaN  357.200012  94.059998
2018-05-17  224.000000  454.200012  2527.0    NaN  359.000000  94.459999
2018-05-18  224.550003  452.000000  2559.0    NaN  358.399994  94.220001
2018-05-22  223.899994  455.000000  2570.0    NaN  359.700012  94.680000
2018-05-23  219.250000  451.600006  2541.0    NaN  352.299988  91.099998
2018-05-24  219.000000  449.500000  2546.0    NaN  351.200012  90.760002
2018-05-25  217.600006  445.700012  2569.0    NaN  354.000000  90.639999
2018-05-28  217.500000  447.100006  2573.0    NaN  353.899994  91.019997
2018-05-29  216.149994  442.000000  2570.0    NaN  342.700012  87.879997
2018-05-30  214.000000  441.799988  2551.0    NaN  342.500000  87.500000
2018-05-31  211.050003  439.600006  2549.0    NaN  336.000000  85.180000
2018-06-01  215.949997  443.299988  2601.0    NaN  344.600006  87.160004
2018-06-04  214.199997  448.600006  2605.0    NaN  347.100006  87.739998
2018-06-05  210.199997  444.299988  2595.0    NaN  341.500000  87.059998
2018-06-06  209.850006  441.299988  2613.0    NaN  341.299988  86.800003
2018-06-07  210.000000  443.500000  2603.0    NaN  344.799988  87.260002
2018-06-08  207.699997  442.299988  2611.0    NaN  342.299988  87.059998
2018-06-11  209.649994  447.700012  2645.0    NaN  349.399994  88.639999
2018-06-12  209.750000  449.100006  2654.0    NaN  348.799988  88.820000
2019-02-14  271.149994  449.000000  2487.0    NaN  415.899994  96.919998

Attributes
Symbols       UBSG.VX      UHR.VX     ZURN.VX
Date
2017-01-03  16.021774  304.813232  259.839447
2017-01-04  16.424717  303.168701  260.838867
2017-01-05  16.280807  300.460114  259.657745
2017-01-06  16.309589  302.201355  259.476074
2017-01-09  16.117712  310.617340  258.567505
2017-01-10  16.098526  319.420258  258.113281
2017-01-11  16.069744  320.871277  258.204132
2017-01-12  16.021774  338.380371  254.660843
2017-01-13  16.635782  342.056335  257.749847
2017-01-16  16.347967  338.864044  255.751068
2017-01-17  16.223246  334.897919  252.843765
2017-01-18  15.877865  333.156647  252.571243
2017-01-19  16.088932  336.735901  251.026703
2017-01-20  16.012180  333.930573  252.298676
2017-01-23  15.810708  332.479523  251.208435
2017-01-24  16.127306  336.445648  252.752945
2017-01-25  16.530249  344.377991  261.565674
2017-01-26  16.328779  343.217133  262.201660
2017-01-27  15.590050  339.251007  263.201019
2017-01-30  15.484516  335.188110  258.294952
2017-01-31  15.321422  338.090179  257.568146
2017-02-01  15.263858  339.251007  260.021179
2017-02-02  15.071980  342.636749  257.568146
2017-02-03  15.350203  336.155457  260.475433
2017-02-06  15.177512  328.900330  259.112640
2017-02-07  15.148731  327.546021  258.840088
2017-02-08  15.139137  324.643951  258.022400
2017-02-09  15.331015  324.063538  256.659607
2017-02-10  15.331015  324.063538  256.659607
2017-02-13  15.244670  328.803558  255.387680
...               ...         ...         ...
2018-04-30  16.088932  471.117279  317.600006
2018-05-02  15.949820  473.972534  320.000000
2018-05-03  15.714769  466.292877  315.899994
2018-05-04  15.940226  463.831451  317.299988
2018-05-07  15.354999  467.868195  317.899994
2018-05-08  16.075001  469.640411  317.000000
2018-05-09  16.215000  468.754303  318.299988
2018-05-11  16.430000  475.843201  317.299988
2018-05-14  16.290001  475.154022  314.799988
2018-05-15  16.309999  480.076874  315.500000
2018-05-16  16.049999  481.356812  313.899994
2018-05-17  16.139999  483.621338  315.799988
2018-05-18  15.995000  478.107727  314.899994
2018-05-22  16.320000  487.658051  312.600006
2018-05-23  16.025000  476.335480  306.799988
2018-05-24  15.820000  480.470703  306.600006
2018-05-25  15.765000  478.600006  305.799988
2018-05-28  15.725000  477.000000  305.399994
2018-05-29  15.240000  474.600006  296.399994
2018-05-30  15.175000  475.000000  295.399994
2018-05-31  14.850000  478.200012  292.200012
2018-06-01  15.315000  487.899994  296.899994
2018-06-04  15.470000  488.299988  297.899994
2018-06-05  15.060000  491.399994  295.200012
2018-06-06  15.205000  495.100006  293.700012
2018-06-07  15.310000  485.000000  296.700012
2018-06-08  15.195000  492.500000  294.700012
2018-06-11  15.700000  497.399994  299.700012
2018-06-12  15.725000  490.000000  302.000000
2019-02-14  12.920000  289.200012  319.799988

[362 rows x 120 columns]

In [6]:
xxx=a["Adj Close"]

In [7]:
xxx.to_csv("smi2017_adjclose2.txt")

In [8]:
xxx.apply(lambda x: len(x.dropna()))

Symbols
ABBN.VX    362
ADEN.VX    362
BAER.VX    362
CFR.VX     362
CSGN.VX    362
GEBN.VX    362
GIVN.VX    362
LHN.VX     362
LONN.VX    362
NESN.VX    362
NOVN.VX    362
ROG.VX     362
SCMN.VX    362
SGSN.VX    362
SIK.VX       0
SLHN.VX    362
SREN.VX    362
UBSG.VX    362
UHR.VX     362
ZURN.VX    362
dtype: int64

In [9]:
xxx

Symbols,ABBN.VX,ADEN.VX,BAER.VX,CFR.VX,CSGN.VX,GEBN.VX,GIVN.VX,LHN.VX,LONN.VX,NESN.VX,NOVN.VX,ROG.VX,SCMN.VX,SGSN.VX,SIK.VX,SLHN.VX,SREN.VX,UBSG.VX,UHR.VX,ZURN.VX
Date,,,,,,,,,,,,,,,,,,,,
2017-01-03,20.266804,61.434513,47.669998,65.862610,14.994900,390.473328,1754.370117,51.577847,163.860992,68.356392,69.855576,236.000000,410.591125,2094.0,NaN,296.500000,82.766937,16.021774,304.813232,259.839447
2017-01-04,20.294785,63.162495,48.139999,65.128082,15.515900,387.615509,1767.582153,51.770844,169.139999,68.920563,69.204025,238.100006,417.127197,2091.0,NaN,298.500000,83.148743,16.424717,303.168701,260.838867
2017-01-05,20.304110,63.162495,48.430000,64.785301,15.207100,391.235443,1768.525757,52.060333,170.067001,69.672752,69.715965,241.199997,423.754028,2104.0,NaN,298.000000,82.342712,16.280807,300.460114,259.657745
2017-01-06,20.462664,63.117023,47.860001,66.009514,15.332600,390.854370,1763.807251,52.253330,170.807999,70.142876,69.576340,241.300003,424.026398,2101.0,NaN,298.299988,82.130600,16.309589,302.201355,259.476074
2017-01-09,20.378723,63.071552,47.200001,66.793007,15.351900,390.282837,1760.032349,51.770844,170.158997,70.236908,69.809036,241.899994,423.209351,2114.0,NaN,297.100006,81.494255,16.117712,310.617340,258.567505
2017-01-10,20.630545,63.526279,47.459999,69.437309,15.332600,390.759125,1741.157959,52.012085,170.623001,69.860809,70.181351,243.399994,419.305878,2098.0,NaN,294.299988,81.324562,16.098526,319.420258,258.113281
2017-01-11,21.087551,63.753647,47.310001,69.437309,15.467700,393.426422,1754.370117,51.384853,172.660004,69.860809,69.297104,240.800003,418.761200,2116.0,NaN,295.200012,81.579102,16.069744,320.871277,258.204132
2017-01-12,20.863710,64.162918,47.180000,75.411461,15.101000,393.140625,1746.820312,51.143608,170.899994,70.001839,67.761314,235.899994,416.673309,2121.0,NaN,294.299988,80.857918,16.021774,338.380371,254.660843
2017-01-13,21.143509,64.208382,48.139999,75.803215,15.554500,394.379028,1743.989136,52.349827,171.548996,70.048859,67.947464,239.000000,418.670441,2146.0,NaN,295.600006,81.791214,16.635782,342.056335,257.749847
2017-01-16,20.956976,63.708183,47.779999,75.215591,15.294000,395.522156,1722.283691,50.757618,170.067001,69.625748,67.109756,235.600006,412.406677,2139.0,NaN,292.600006,79.797340,16.347967,338.864044,255.751068
2017-01-17,20.901016,63.662704,47.849998,74.823845,15.120300,404.476685,1711.902710,50.323383,168.770004,68.967560,66.411667,234.699997,410.681915,2090.0,NaN,292.899994,79.161003,16.223246,334.897919,252.843765
2017-01-18,20.966303,63.480816,47.299999,74.432091,14.744000,404.095642,1704.353027,49.406658,170.345001,69.343666,67.202827,235.600006,408.140137,2088.0,NaN,292.399994,78.821617,15.877865,333.156647,252.571243
2017-01-19,21.143509,64.344810,47.049999,75.117645,14.859800,402.380920,1715.677734,49.310158,169.789001,68.826523,66.178970,233.000000,405.507568,2090.0,NaN,296.399994,78.482231,16.088932,336.735901,251.026703
2017-01-20,21.292734,64.299324,46.630001,74.676933,15.004500,400.761505,1709.071655,49.261909,169.882004,68.967560,65.992813,233.500000,401.059387,2094.0,NaN,295.200012,78.439804,16.012180,333.930573,252.298676
2017-01-23,21.152834,64.481224,45.320000,74.725906,14.608900,401.142548,1716.621338,49.503151,169.882004,68.732498,65.201645,232.199997,398.699188,2051.0,NaN,294.200012,78.100426,15.810708,332.479523,251.208435
2017-01-24,21.302061,65.072380,46.299999,74.970749,14.763300,401.999878,1719.452515,51.240105,169.882004,68.967560,64.736252,231.399994,397.155914,2076.0,NaN,296.000000,78.567078,16.127306,336.445648,252.752945
2017-01-25,21.898966,66.027313,47.070000,76.635674,15.351900,406.762909,1736.439453,52.977058,172.104996,69.390678,66.318588,234.800003,397.609802,2097.0,NaN,303.100006,79.924606,16.530249,344.377991,261.565674
2017-01-26,22.150785,66.163734,47.369999,75.754242,15.294000,408.191803,1711.902710,52.349827,172.753006,68.450432,66.923599,235.699997,396.974365,2101.0,NaN,302.899994,79.161003,16.328779,343.217133,262.201660
2017-01-27,22.150785,64.708588,46.090000,75.607330,14.744000,404.857697,1722.283691,52.156830,169.789001,68.779518,66.923599,236.300003,396.702026,2104.0,NaN,300.799988,79.754921,15.590050,339.251007,263.201019
2017-01-30,21.936275,64.071960,46.110001,74.774872,14.666800,401.142548,1749.651489,51.433102,169.604004,68.074326,67.016678,234.000000,393.433990,2088.0,NaN,298.500000,78.524658,15.484516,335.188110,258.294952
2017-01-31,21.852335,64.026497,46.240002,75.117645,14.464200,401.618835,1678.872681,51.047112,167.565994,67.980301,67.435532,233.000000,394.886475,2092.0,NaN,299.100006,78.142853,15.321422,338.090179,257.568146
2017-02-01,21.898966,64.663116,46.820000,74.285187,14.647500,400.951996,1644.898926,51.770844,162.378998,67.839264,67.528610,237.500000,393.070892,2073.0,NaN,306.200012,79.203423,15.263858,339.251007,260.021179
2017-02-02,21.852335,64.708588,46.290001,74.285187,14.300100,400.856750,1626.024536,52.349827,161.638000,67.698227,67.109756,233.500000,390.619843,2074.0,NaN,303.299988,79.415535,15.071980,342.636749,257.568146
2017-02-03,21.870989,64.526688,46.750000,73.991379,14.551000,402.190399,1619.418579,53.121803,161.914993,68.497437,67.900917,235.800003,392.526215,2076.0,NaN,308.100006,80.094299,15.350203,336.155457,260.475433
2017-02-06,21.619169,64.481224,46.860001,72.669228,14.425600,400.189941,1629.799438,52.784065,159.229004,68.309395,68.273239,236.100006,391.436890,2062.0,NaN,306.500000,79.670074,15.177512,328.900330,259.112640
2017-02-07,21.749741,64.344810,46.880001,73.207878,14.290500,402.380920,1651.504883,52.398075,162.378998,68.497437,68.831711,238.500000,394.523376,2068.0,NaN,306.700012,79.585228,15.148731,327.546021,258.840088
2017-02-08,21.012938,63.071552,47.070000,72.228508,13.894800,404.762451,1670.379272,52.398075,161.729996,69.672752,68.971329,237.399994,399.970062,2085.0,NaN,303.899994,79.839760,15.139137,324.643951,258.022400
2017-02-09,21.246103,63.526279,47.220001,72.865105,14.145700,405.143463,1669.435547,53.845535,163.860992,69.531708,69.809036,239.899994,403.328857,2092.0,NaN,308.100006,80.773064,15.331015,324.063538,256.659607
2017-02-10,21.246103,63.526279,47.220001,72.865105,14.145700,405.143463,1669.435547,53.845535,163.860992,69.531708,69.809036,239.899994,403.328857,2092.0,NaN,308.100006,80.773064,15.331015,324.063538,256.659607
2017-02-13,21.451288,64.617645,47.830002,74.334160,14.242200,408.001282,1665.660645,54.569263,164.694000,69.249641,70.274437,240.000000,401.331726,2114.0,NaN,311.299988,79.924606,15.244670,328.803558,255.387680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-04-30,23.240000,65.940002,59.240002,94.559998,16.795000,424.600006,2219.000000,55.360001,244.199997,76.980003,76.699997,220.850006,477.000000,2417.0,NaN,348.500000,94.660004,16.088932,471.117279,317.600006
2018-05-02,23.490000,66.500000,59.779999,95.540001,16.750000,430.899994,2226.000000,55.840000,246.800003,76.379997,76.400002,223.649994,460.299988,2428.0,NaN,349.700012,93.500000,15.949820,473.972534,320.000000
2018-05-03,23.170000,65.839996,59.480000,94.459999,16.455000,441.899994,2199.000000,55.639999,243.600006,75.800003,76.019997,224.949997,456.000000,2423.0,NaN,346.600006,93.220001,15.714769,466.292877,315.899994
2018-05-04,23.389999,66.139999,59.939999,95.000000,16.405001,443.000000,2193.000000,56.220001,256.200012,76.360001,76.760002,225.800003,455.500000,2437.0,NaN,347.500000,92.800003,15.940226,463.831451,317.299988
2018-05-07,23.820000,67.440002,61.020000,95.639999,16.575001,445.700012,2227.000000,56.340000,265.700012,77.559998,77.599998,227.850006,460.700012,2456.0,NaN,350.500000,93.620003,15.354999,467.868195,317.899994
2018-05-08,23.950001,64.000000,60.919998,95.800003,16.629999,445.299988,2243.000000,54.619999,261.700012,76.800003,77.720001,225.699997,458.299988,2482.0,NaN,353.299988,94.279999,16.075001,469.640411,317.000000
2018-05-09,23.920000,64.120003,61.580002,96.379997,16.799999,445.600006,2266.000000,55.020000,263.200012,77.400002,77.699997,226.000000,458.899994,2506.0,NaN,357.899994,94.639999,16.215000,468.754303,318.299988
2018-05-11,24.080000,64.400002,62.820000,96.580002,17.145000,447.600006,2286.000000,52.840000,265.899994,77.599998,77.559998,222.149994,460.399994,2515.0,NaN,360.299988,95.139999,16.430000,475.843201,317.299988
2018-05-14,23.879999,64.080002,62.880001,97.760002,16.920000,444.799988,2267.000000,52.520000,266.299988,77.300003,78.220001,224.800003,458.200012,2509.0,NaN,358.500000,94.279999,16.290001,475.154022,314.799988
2018-05-15,23.830000,63.500000,62.860001,97.360001,16.980000,442.500000,2277.000000,52.939999,264.000000,76.980003,77.980003,225.699997,454.899994,2490.0,NaN,360.399994,94.519997,16.309999,480.076874,315.500000
2018-05-16,23.959999,63.340000,62.160000,97.959999,16.715000,442.100006,2274.000000,53.000000,262.899994,76.940002,77.779999,226.199997,450.700012,2500.0,NaN,357.200012,94.059998,16.049999,481.356812,313.899994
2018-05-17,24.100000,63.360001,62.540001,99.019997,16.860001,445.899994,2279.000000,53.439999,263.700012,77.180000,77.639999,224.000000,454.200012,2527.0,NaN,359.000000,94.459999,16.139999,483.621338,315.799988
2018-05-18,24.340000,63.360001,62.299999,93.800003,16.650000,443.100006,2270.000000,53.240002,267.000000,77.099998,77.000000,224.550003,452.000000,2559.0,NaN,358.399994,94.220001,15.995000,478.107727,314.899994
2018-05-22,24.520000,63.980000,63.160000,93.120003,16.930000,445.399994,2259.000000,53.740002,271.600006,76.040001,76.680000,223.899994,455.000000,2570.0,NaN,359.700012,94.680000,16.320000,487.658051,312.600006
2018-05-23,23.820000,62.060001,61.000000,92.019997,16.445000,438.899994,2223.000000,52.560001,267.600006,75.639999,76.160004,219.250000,451.600006,2541.0,NaN,352.299988,91.099998,16.025000,476.335480,306.799988
2018-05-24,23.500000,61.820000,60.340000,92.540001,16.215000,437.399994,2218.000000,52.320000,267.600006,76.059998,75.660004,219.000000,449.500000,2546.0,NaN,351.200012,90.760002,15.820000,480.470703,306.600006
2018-05-25,23.360001,61.480000,60.799999,92.620003,16.150000,435.799988,2230.000000,52.139999,269.100006,76.199997,75.559998,217.600006,445.700012,2569.0,NaN,354.000000,90.639999,15.765000,478.600006,305.799988
2018-05-28,23.330000,61.360001,60.880001,93.139999,16.070000,434.399994,2232.000000,52.099998,271.399994,76.800003,75.779999,217.500000,447.100006,2573.0,NaN,353.899994,91.019997,15.725000,477.000000,305.399994
2018-05-29,22.889999,60.139999,59.599998,91.580002,15.475000,430.100006,2219.000000,51.220001,268.100006,76.099998,74.599998,216.149994,442.000000,2570.0,NaN,342.700012,87.879997,15.240000,474.600006,296.399994
2018-05-30,22.690001,59.680000,58.540001,90.599998,15.300000,426.799988,2214.000000,51.080002,267.600006,75.260002,74.519997,214.000000,441.799988,2551.0,NaN,342.500000,87.500000,15.175000,475.000000,295.399994
2018-05-31,22.290001,59.119999,57.500000,90.339996,15.020000,425.799988,2195.000000,50.439999,263.700012,74.379997,72.959999,211.050003,439.600006,2549.0,NaN,336.000000,85.180000,14.850000,478.200012,292.200012
2018-06-01,22.879999,60.340000,58.459999,91.260002,15.395000,434.799988,2224.000000,51.400002,266.500000,75.000000,74.699997,215.949997,443.299988,2601.0,NaN,344.600006,87.160004,15.315000,487.899994,296.899994
2018-06-04,22.840000,60.259998,59.340000,91.959999,15.510000,434.500000,2232.000000,51.660000,268.399994,75.279999,74.699997,214.199997,448.600006,2605.0,NaN,347.100006,87.739998,15.470000,488.299988,297.899994
2018-06-05,22.730000,59.900002,58.380001,92.059998,15.165000,434.100006,2196.000000,51.480000,266.299988,74.599998,73.959999,210.199997,444.299988,2595.0,NaN,341.500000,87.059998,15.060000,491.399994,295.200012
2018-06-06,22.709999,59.799999,58.840000,92.919998,15.295000,440.000000,2209.000000,51.660000,267.200012,74.080002,73.980003,209.850006,441.299988,2613.0,NaN,341.299988,86.800003,15.205000,495.100006,293.700012
2018-06-07,22.690001,60.119999,59.139999,91.580002,15.345000,439.100006,2210.000000,52.000000,266.899994,73.699997,74.260002,210.000000,443.500000,2603.0,NaN,344.799988,87.260002,15.310000,485.000000,296.700012
2018-06-08,22.660000,59.740002,59.180000,92.260002,15.185000,439.000000,2203.000000,51.860001,268.000000,73.459999,73.860001,207.699997,442.299988,2611.0,NaN,342.299988,87.059998,15.195000,492.500000,294.700012
2018-06-11,22.879999,60.000000,60.259998,92.559998,15.695000,442.399994,2224.000000,52.180000,272.899994,74.199997,74.500000,209.649994,447.700012,2645.0,NaN,349.399994,88.639999,15.700000,497.399994,299.700012
2018-06-12,23.020000,60.200001,60.380001,92.120003,15.660000,441.000000,2235.000000,52.480000,271.000000,74.540001,74.680000,209.750000,449.100006,2654.0,NaN,348.799988,88.820000,15.725000,490.000000,302.000000
2019-02-14,19.600000,52.619999,40.279999,72.800003,11.795000,393.299988,2482.000000,47.840000,287.100006,89.519997,89.760002,271.149994,449.000000,2487.0,NaN,415.899994,96.919998,12.920000,289.200012,319.799988