In [10]:
import pandas as pd

In [11]:
smi=pd.read_csv("smi.txt", index_col="Ticker")

In [12]:
smi

                                   Company
Ticker
CSGN.VX             Credit Suisse Group AG
NESN.VX                        Nestlé S.A.
SGSN.VX                             SGS SA
UBSG.VX                       UBS Group AG
LONN.VX                    Lonza Group Ltd
ROG.VX                    Roche Holding AG
SIK.VX                             Sika AG
UHR.VX                 The Swatch Group AG
NOVN.VX                        Novartis AG
ABBN.VX                            ABB Ltd
GIVN.VX                        Givaudan SA
SLHN.VX              Swiss Life Holding AG
BAER.VX             Julius Baer Group Ltd.
GEBN.VX                         Geberit AG
ADEN.VX                    Adecco Group AG
ZURN.VX          Zurich Insurance Group AG
SCMN.VX                        Swisscom AG
CFR.VX   Compagnie Financière Richemont SA
LHN.VX                   LafargeHolcim Ltd
SREN.VX                       Swiss Re Ltd

In [13]:
import pandas_datareader as pdr
a=pdr.get_data_yahoo(list(smi.index), start=pd.Timestamp("2017-01-01"))

In [14]:
a

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 173 (major_axis) x 20 (minor_axis)
Items axis: Adj Close to Volume
Major_axis axis: 2017-01-03 00:00:00 to 2017-09-08 00:00:00
Minor_axis axis: ABBN.VX to ZURN.VX

In [15]:
xxx=a["Adj Close"]

In [16]:
xxx.to_csv("smi2017_adjclose2.txt")

In [17]:
xxx.apply(lambda x: len(x.dropna()))

ABBN.VX    173
ADEN.VX    173
BAER.VX    173
CFR.VX     173
CSGN.VX    173
GEBN.VX    173
GIVN.VX    173
LHN.VX     173
LONN.VX    173
NESN.VX    173
NOVN.VX     20
ROG.VX     173
SCMN.VX    173
SGSN.VX    173
SIK.VX     173
SLHN.VX    173
SREN.VX    173
UBSG.VX    173
UHR.VX     173
ZURN.VX    173
dtype: int64

In [18]:
xxx

,ABBN.VX,ADEN.VX,BAER.VX,CFR.VX,CSGN.VX,GEBN.VX,GIVN.VX,LHN.VX,LONN.VX,NESN.VX,NOVN.VX,ROG.VX,SCMN.VX,SGSN.VX,SIK.VX,SLHN.VX,SREN.VX,UBSG.VX,UHR.VX,ZURN.VX
Date,,,,,,,,,,,,,,,,,,,,
2017-01-03,21.003435,66.195396,47.669998,67.250000,14.292187,400.284698,1802.939697,51.577847,163.860992,70.522781,NaN,228.507935,430.602203,2026.138916,4814.334961,296.500000,87.213905,16.700001,309.589844,274.490723
2017-01-04,21.032433,68.057281,48.139999,66.500000,14.788771,397.355072,1816.517578,51.770844,169.139999,71.104820,NaN,230.541275,437.456818,2023.236084,4791.681641,298.500000,87.616226,17.120001,307.919556,275.546478
2017-01-05,21.042099,68.057281,48.430000,66.150002,14.494442,401.065948,1817.487427,52.060333,170.067001,71.880859,NaN,233.542862,444.406616,2035.814819,4784.787109,298.000000,86.766884,16.969999,305.168518,274.298767
2017-01-06,21.206415,68.008293,47.860001,67.400002,14.614060,400.675323,1812.638184,52.253330,170.807999,72.365883,NaN,233.639679,444.692261,2032.911987,4716.826660,298.299988,86.543381,17.000000,306.937042,274.106842
2017-01-09,21.119423,67.959290,47.200001,68.199997,14.632457,400.089417,1808.758789,51.770844,170.158997,72.462883,NaN,234.220627,443.835419,2045.490723,4740.465332,297.100006,85.872841,16.799999,315.484924,273.147064
2017-01-10,21.380396,68.449265,47.459999,70.900002,14.614060,400.577698,1789.361938,52.012085,170.835007,72.074875,NaN,235.673004,439.741699,2030.009277,4728.645996,294.299988,85.694031,16.780001,324.425781,272.667206
2017-01-11,21.854013,68.694252,47.310001,70.900002,14.742829,403.311981,1802.939697,51.384853,172.660004,72.074875,NaN,233.155563,439.170471,2047.425903,4751.299316,295.200012,85.962250,16.750000,325.899567,272.763184
2017-01-12,21.622038,69.135231,47.180000,77.000000,14.393314,403.019043,1795.181030,51.143608,170.899994,72.220375,NaN,228.411102,436.980804,2052.263916,4726.676270,294.299988,85.202316,16.700001,343.683014,269.020111
2017-01-13,21.912006,69.184227,48.139999,77.400002,14.825562,404.288544,1792.271484,52.349827,171.548996,72.268875,NaN,231.412704,439.075287,2076.453613,4758.193848,295.600006,86.185760,17.340000,347.416595,272.283295
2017-01-16,21.718693,68.645256,47.779999,76.800003,14.577270,405.460388,1769.965088,50.757618,170.067001,71.832359,NaN,228.120636,432.506256,2069.680664,4723.721191,292.600006,84.084755,17.040001,344.174286,270.171814
2017-01-17,21.660700,68.596260,47.849998,76.400002,14.411710,414.639893,1759.296753,50.323383,168.770004,71.153320,NaN,227.249207,430.697418,2022.268555,4708.947266,292.899994,83.414223,16.910000,340.145996,267.100586
2017-01-18,21.728359,68.400276,47.299999,76.000000,14.053045,414.249268,1751.537964,49.406658,170.001007,71.541336,NaN,228.120636,428.031769,2020.333374,4725.691406,292.399994,83.056602,16.549999,338.377441,266.812683
2017-01-19,21.912006,69.331215,47.049999,76.699997,14.163418,412.491486,1763.176147,49.310158,169.815994,71.007805,NaN,225.603180,425.270874,2022.268555,4742.435059,296.399994,82.698982,16.770000,342.012756,265.181061
2017-01-20,22.066656,69.282219,46.630001,76.250000,14.301337,410.831390,1756.387207,49.261909,169.882004,71.153320,NaN,226.087296,420.605927,2026.138916,4752.284180,295.200012,82.654282,16.690001,339.163483,266.524750
2017-01-23,21.921671,69.478210,45.320000,76.300003,13.924276,411.221985,1764.145996,49.503151,169.882004,70.910805,NaN,224.828568,418.130676,1984.532471,4773.952637,294.200012,82.296669,16.480000,337.689728,265.373047
2017-01-24,22.076323,70.115181,46.299999,76.550003,14.071440,412.100861,1767.055542,51.240105,169.882004,71.153320,NaN,224.053970,416.512207,2008.722290,4837.973145,296.000000,82.788391,16.809999,341.717987,267.004639
2017-01-25,22.694921,71.144119,47.070000,78.250000,14.632457,416.983582,1784.512695,52.977058,172.104996,71.589844,NaN,227.346039,416.988220,2029.041626,4954.194824,303.100006,84.218864,17.230000,349.774597,276.314270
2017-01-26,22.955894,71.291115,47.369999,77.349998,14.577270,418.448395,1759.296753,52.349827,172.753006,70.619797,NaN,228.217453,416.321808,2032.911987,4998.516602,302.899994,83.414223,17.020000,348.595581,276.986115
2017-01-27,22.955894,69.723198,46.090000,77.199997,14.053045,415.030487,1769.965088,52.156830,169.789001,70.959312,NaN,228.798416,416.036194,2035.814819,5023.139648,300.799988,84.040054,16.250000,344.567291,278.041840
2017-01-30,22.733585,69.037231,46.110001,76.349998,13.979462,411.514954,1798.090576,51.481346,169.604004,70.231773,NaN,226.571426,412.608887,2020.333374,5057.612305,298.100006,82.743690,16.139999,340.440735,272.859131
2017-01-31,22.646595,68.988235,46.240002,76.699997,13.786357,411.710266,1725.352295,51.047112,167.565994,70.134766,NaN,225.603180,414.132141,2024.203735,5106.858887,299.100006,82.341370,15.970000,343.388275,272.091339
2017-02-01,22.694921,69.674202,46.820000,75.849998,13.961067,411.026672,1690.437866,51.770844,162.378998,69.989258,NaN,229.960312,412.228088,2005.819458,5121.632813,306.200012,83.458923,15.910000,344.567291,274.682709
2017-02-02,22.646595,69.723198,46.290001,75.849998,13.629948,410.929016,1671.041016,52.349827,161.638000,69.843750,NaN,226.087296,409.657593,2006.786987,5146.255859,303.299988,83.682442,15.710000,348.006104,272.091339
2017-02-03,22.665926,69.527206,46.750000,75.550003,13.869089,412.296204,1664.252075,53.121803,162.033997,70.668289,NaN,228.314285,411.656860,2008.722290,5185.653320,308.100006,84.397675,16.000000,341.423248,275.162567
2017-02-06,22.404953,69.478210,46.860001,74.199997,13.749566,410.245453,1674.920410,52.784065,159.229004,70.474281,NaN,228.604767,410.514435,1995.175903,5180.728516,306.500000,83.950653,15.820000,334.054413,273.722931
2017-02-07,22.540272,69.331215,46.880001,74.750000,13.620797,412.491486,1697.226807,52.398075,162.378998,70.668289,NaN,230.928574,413.751343,2000.981445,5185.653320,306.700012,83.861252,15.790000,332.678894,273.434998
2017-02-08,21.776688,67.959290,47.070000,73.750000,13.243641,414.932831,1716.623657,52.398075,161.729996,71.880859,NaN,229.863480,419.463501,2017.430542,5229.975098,303.899994,84.129463,15.780000,329.731354,272.571228
2017-02-09,22.018328,68.449265,47.220001,74.400002,13.482783,415.323456,1715.653809,53.845535,163.860992,71.735344,NaN,232.284119,422.985992,2024.203735,5264.447754,308.100006,85.112907,15.980000,329.141846,271.131592
2017-02-10,22.018328,68.449265,47.220001,74.400002,13.482783,415.323456,1715.653809,53.845535,163.860992,71.735344,NaN,232.284119,422.985992,2024.203735,5269.372070,308.100006,85.112907,15.980000,329.141846,271.131592
2017-02-13,22.230972,69.625206,47.830002,75.900002,13.574760,418.253082,1711.774414,54.569263,164.694000,71.444336,NaN,232.380951,420.891541,2045.490723,5323.543457,311.299988,84.218864,15.890000,333.956146,269.787933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-28,22.670000,73.050003,54.099998,81.900002,15.130000,457.799988,1913.000000,57.549999,231.399994,81.699997,NaN,242.500000,471.899994,2157.000000,6650.000000,347.399994,92.800003,16.900000,382.799988,292.700012
2017-07-31,22.700001,73.650002,54.700001,82.150002,14.880000,465.200012,1925.000000,58.049999,230.399994,81.699997,NaN,244.899994,472.700012,2138.000000,6665.000000,353.000000,93.250000,16.820000,383.899994,294.500000
2017-08-02,22.799999,74.449997,55.549999,83.150002,14.920000,473.500000,1973.000000,57.900002,232.000000,82.250000,NaN,246.399994,477.600006,2164.000000,6635.000000,361.600006,94.699997,16.920000,392.000000,298.700012
2017-08-03,22.760000,73.949997,55.750000,84.349998,14.960000,475.600006,1967.000000,58.549999,230.300003,82.599998,NaN,246.899994,479.200012,2175.000000,6735.000000,361.700012,94.949997,16.940001,396.000000,298.600006
2017-08-04,22.750000,74.400002,55.500000,85.349998,15.270000,482.000000,1979.000000,58.950001,228.500000,83.250000,NaN,248.199997,480.500000,2181.000000,6730.000000,362.799988,92.050003,17.350000,398.700012,297.200012
2017-08-07,22.620001,74.599998,55.650002,85.449997,15.270000,483.399994,1971.000000,59.500000,228.199997,83.150002,NaN,247.399994,482.500000,2178.000000,6660.000000,362.899994,91.900002,16.959999,396.100006,298.100006
2017-08-08,22.790001,74.949997,55.299999,85.349998,15.220000,481.899994,1966.000000,59.750000,227.000000,83.250000,NaN,247.399994,482.500000,2186.000000,6670.000000,363.500000,91.650002,16.920000,393.700012,297.500000
2017-08-09,22.350000,73.900002,53.900002,83.800003,14.760000,476.500000,1944.000000,58.450001,224.899994,82.199997,NaN,244.199997,479.700012,2164.000000,6620.000000,354.500000,90.300003,17.350000,382.799988,293.299988
2017-08-10,22.080000,69.400002,53.400002,83.250000,14.530000,472.600006,1928.000000,58.049999,223.000000,81.650002,NaN,243.000000,476.299988,2149.000000,6580.000000,348.299988,88.650002,16.549999,378.000000,292.100006
2017-08-11,21.980000,68.949997,52.450001,82.599998,14.340000,470.200012,1916.000000,57.500000,222.300003,80.849998,NaN,242.300003,472.600006,2127.000000,6590.000000,345.600006,88.250000,17.350000,375.100006,289.200012
2017-08-14,22.290001,70.099998,54.299999,84.150002,14.630000,479.700012,1940.000000,58.200001,224.800003,82.400002,81.500000,244.399994,481.600006,2154.000000,6715.000000,351.000000,89.349998,16.650000,381.899994,294.000000
2017-08-15,22.219999,70.099998,54.299999,84.150002,14.630000,479.700012,1940.000000,58.150002,224.800003,82.400002,81.500000,244.399994,481.600006,2154.000000,6715.000000,351.000000,89.349998,16.650000,377.100006,294.000000
2017-08-16,22.480000,71.199997,54.700001,83.599998,14.590000,479.000000,1954.000000,58.500000,232.199997,81.849998,81.949997,245.100006,478.700012,2169.000000,6715.000000,350.399994,88.699997,16.610001,377.299988,296.200012
2017-08-17,22.480000,71.199997,54.700001,83.599998,14.590000,479.000000,1954.000000,58.500000,232.199997,81.849998,81.949997,245.100006,478.700012,2169.000000,6715.000000,350.399994,88.699997,16.610001,377.299988,296.200012
2017-08-18,21.940001,70.250000,53.900002,82.199997,14.380000,446.500000,1930.000000,57.500000,229.100006,80.849998,79.800003,241.399994,474.600006,2141.000000,6640.000000,346.200012,87.449997,16.230000,371.000000,291.600006
2017-08-21,21.889999,70.300003,53.950001,82.449997,14.260000,452.000000,1935.000000,57.549999,230.199997,81.300003,79.949997,240.399994,479.500000,2144.000000,6695.000000,346.299988,87.650002,16.110001,371.500000,291.700012
2017-08-22,22.309999,71.250000,54.400002,83.750000,14.360000,456.899994,1953.000000,58.200001,234.399994,81.949997,80.650002,243.000000,484.700012,2161.000000,6700.000000,347.200012,88.449997,16.129999,373.799988,292.700012
2017-08-23,22.330000,71.250000,53.549999,84.000000,14.350000,447.000000,1953.000000,58.099998,233.699997,82.050003,80.550003,242.899994,482.700012,2155.000000,6735.000000,345.700012,88.599998,16.090000,374.299988,293.000000
2017-08-24,22.290001,70.650002,53.799999,85.000000,14.360000,445.500000,1967.000000,57.650002,236.500000,81.449997,80.449997,242.500000,481.899994,2157.000000,6750.000000,345.899994,88.500000,16.110001,377.500000,292.700012
2017-08-25,22.260000,69.650002,53.750000,85.250000,14.430000,444.399994,1968.000000,57.250000,237.800003,80.599998,80.199997,242.000000,479.000000,2149.000000,6700.000000,346.700012,87.900002,16.080000,377.600006,292.100006
2017-08-28,22.080000,69.000000,53.650002,85.500000,14.360000,441.100006,1961.000000,57.000000,237.800003,80.349998,79.400002,241.899994,477.000000,2129.000000,6655.000000,344.000000,87.000000,16.010000,376.299988,290.100006
2017-08-29,21.709999,68.449997,53.000000,84.949997,14.000000,439.299988,1948.000000,55.950001,237.100006,80.599998,79.199997,241.100006,474.600006,2112.000000,6655.000000,338.700012,85.500000,15.710000,375.100006,285.299988
2017-08-30,21.900000,69.199997,53.400002,85.050003,14.090000,441.200012,1964.000000,56.099998,242.000000,80.949997,79.250000,241.199997,480.600006,2129.000000,6720.000000,344.799988,86.250000,15.830000,377.799988,286.299988
2017-08-31,22.200001,69.500000,53.599998,85.750000,14.100000,438.100006,1960.000000,56.349998,242.800003,81.349998,80.900002,243.500000,483.600006,2143.000000,6800.000000,343.200012,86.849998,15.800000,382.799988,286.899994
2017-09-01,22.410000,70.050003,54.299999,86.099998,14.170000,439.100006,1973.000000,57.150002,244.500000,81.150002,80.849998,244.199997,481.899994,2150.000000,6875.000000,347.000000,86.949997,17.350000,386.399994,287.200012
2017-09-04,22.450001,69.849998,53.400002,84.900002,14.000000,438.399994,1973.000000,56.849998,243.100006,80.250000,80.050003,242.699997,477.600006,2142.000000,6870.000000,342.200012,85.849998,15.700000,378.000000,285.000000
2017-09-05,22.610001,69.750000,53.049999,86.000000,13.920000,438.500000,1977.000000,56.500000,244.000000,80.949997,80.099998,242.300003,476.000000,2136.000000,6800.000000,337.299988,84.500000,15.510000,377.200012,282.500000
2017-09-06,22.730000,69.699997,53.349998,86.099998,14.010000,438.500000,1973.000000,55.950001,242.500000,80.550003,80.099998,242.600006,475.100006,2176.000000,6800.000000,335.399994,83.750000,15.560000,375.399994,280.500000
2017-09-07,22.809999,70.099998,53.250000,87.349998,13.900000,441.799988,2009.000000,56.200001,245.800003,80.949997,80.949997,242.899994,477.600006,2193.000000,6935.000000,333.100006,82.900002,17.350000,380.700012,280.000000
2017-09-08,22.750000,70.400002,53.400002,87.150002,13.970000,442.500000,2017.000000,56.599998,247.899994,80.650002,81.000000,244.600006,476.500000,2187.000000,6935.000000,333.700012,83.349998,15.560000,383.000000,279.799988